-- Table: public.ngha_cvg

-- DROP TABLE public.ngha_cvg;

CREATE TABLE public.ngha_cvg
(
    coverage_id numeric(18,0) NOT NULL,
    coverage_type_c numeric(38,0),
    coverage_status_c numeric(38,0),
    carrier_id character varying(18) COLLATE pg_catalog."default",
    payor_id numeric(18,0),
    plan_id numeric(18,0),
    plan_grp_id character varying(20) COLLATE pg_catalog."default",
    subscr_num character varying(50) COLLATE pg_catalog."default",
    acct_id numeric(18,0),
    subscr_name character varying(160) COLLATE pg_catalog."default",
    cobra_status_yn character varying(1) COLLATE pg_catalog."default",
    cobra_date date,
    late_enroll_yn character varying(1) COLLATE pg_catalog."default",
    student_review_dt date,
    employment_date date,
    application_date date,
    pb_acct_id character varying(18) COLLATE pg_catalog."default",
    subscr_birthdate date,
    subscr_sex_c character varying(66) COLLATE pg_catalog."default",
    subscr_addr1 character varying(300) COLLATE pg_catalog."default",
    subscr_addr2 character varying(150) COLLATE pg_catalog."default",
    subscr_city character varying(40) COLLATE pg_catalog."default",
    subscr_state_c character varying(66) COLLATE pg_catalog."default",
    subscr_country_c character varying(66) COLLATE pg_catalog."default",
    subscr_zip character varying(50) COLLATE pg_catalog."default",
    subscr_phone character varying(50) COLLATE pg_catalog."default",
    subscriber_fax character varying(25) COLLATE pg_catalog."default",
    subscr_work_phone character varying(50) COLLATE pg_catalog."default",
    cvg_eff_dt date,
    cvg_term_dt date,
    subscr_county_c character varying(66) COLLATE pg_catalog."default",
    casehead_number character varying(40) COLLATE pg_catalog."default",
    casehead_name character varying(40) COLLATE pg_catalog."default",
    dt_last_pro_rated date,
    tnsfrd_coverage_id numeric(18,0),
    update_date date,
    subsc_race_c numeric(38,0),
    sub_marital_sts_c numeric(38,0),
    is_sub_us_citzn_yn character varying(1) COLLATE pg_catalog."default",
    cvg_reg_status_c character varying(66) COLLATE pg_catalog."default",
    last_date_verified date,
    next_review_date date,
    verify_user_id character varying(18) COLLATE pg_catalog."default",
    verify_source_c numeric(38,0),
    subscr_employer_id character varying(254) COLLATE pg_catalog."default",
    group_name character varying(254) COLLATE pg_catalog."default",
    cvg_addr1 character varying(150) COLLATE pg_catalog."default",
    cvg_addr2 character varying(80) COLLATE pg_catalog."default",
    cvg_city character varying(40) COLLATE pg_catalog."default",
    state_c character varying(66) COLLATE pg_catalog."default",
    cvg_zip character varying(50) COLLATE pg_catalog."default",
    cvg_phone1 character varying(50) COLLATE pg_catalog."default",
    subscr_ssn character varying(192) COLLATE pg_catalog."default",
    subscr_eep_addr_1 character varying(80) COLLATE pg_catalog."default",
    subscr_eep_addr_2 character varying(80) COLLATE pg_catalog."default",
    subscr_eep_city character varying(40) COLLATE pg_catalog."default",
    subscr_eep_ste_c character varying(66) COLLATE pg_catalog."default",
    subscr_eep_zip character varying(50) COLLATE pg_catalog."default",
    subscr_eep_phone character varying(50) COLLATE pg_catalog."default",
    subscr_emp_stat_c numeric(38,0),
    group_num character varying(254) COLLATE pg_catalog."default",
    claim_mail_code_c numeric(38,0),
    cm_phy_owner_id character varying(25) COLLATE pg_catalog."default",
    cm_log_owner_id character varying(25) COLLATE pg_catalog."default",
    web_apn_id character varying(18) COLLATE pg_catalog."default",
    wc_employer_id character varying(254) COLLATE pg_catalog."default",
    wc_date_of_injury date,
    is_sig_on_file_yn character varying(1) COLLATE pg_catalog."default",
    enroll_reason_c numeric(38,0),
    cvg_term_reason_c numeric(38,0),
    subscr_empr_id_cmt character varying(254) COLLATE pg_catalog."default",
    pat_rec_of_subs_id character varying(18) COLLATE pg_catalog."default",
    ecd_table_def_copay numeric(18,2),
    coinsurance_ovr numeric(3,0),
    subscr_house_num character varying(254) COLLATE pg_catalog."default",
    medc_covered_left numeric(18,0),
    medc_coins_left numeric(18,0),
    medc_reserve_left numeric(18,0),
    ccs_pat_id character varying(254) COLLATE pg_catalog."default",
    ccs_dx character varying(254) COLLATE pg_catalog."default",
    ccs_cc_name character varying(254) COLLATE pg_catalog."default",
    ccs_coor_phone character varying(254) COLLATE pg_catalog."default",
    ccs_county_phone character varying(254) COLLATE pg_catalog."default",
    cvg_county_c character varying(66) COLLATE pg_catalog."default",
    cvg_country_c character varying(66) COLLATE pg_catalog."default",
    cvg_house_num character varying(20) COLLATE pg_catalog."default",
    cvg_district_c numeric(38,0),
    subscr_eep_cnty_c character varying(66) COLLATE pg_catalog."default",
    subscr_eep_house_n character varying(20) COLLATE pg_catalog."default",
    subscr_eep_dist_c numeric(38,0),
    subscr_district_c numeric(38,0),
    eff_hosp_cvg_dt date,
    eff_prov_cvg_dt date,
    medicare_cvg_type_c numeric(38,0),
    medicare_subscr_id character varying(254) COLLATE pg_catalog."default",
    rqg_rel_to_sub_c numeric(38,0),
    q4co_buckets_exc_yn character varying(1) COLLATE pg_catalog."default",
    med_sec_type_c character varying(66) COLLATE pg_catalog."default",
    chdp_county_c character varying(66) COLLATE pg_catalog."default",
    chdp_aid_code character varying(254) COLLATE pg_catalog."default",
    subsc_rel_to_guar_c numeric(38,0),
    subscr_empr_cntry_c character varying(66) COLLATE pg_catalog."default",
    cvg_card_issue_dt date,
    cvg_deductible_yn character varying(1) COLLATE pg_catalog."default",
    first_spec_aid_code character varying(254) COLLATE pg_catalog."default",
    sec_spec_aid_code character varying(254) COLLATE pg_catalog."default",
    thrd_spec_aid_code character varying(254) COLLATE pg_catalog."default",
    evc_num character varying(254) COLLATE pg_catalog."default",
    county_code_c numeric(38,0),
    cvg_verification_id numeric(18,0),
    ext_routing_num_c character varying(66) COLLATE pg_catalog."default",
    conf_nam_of_assc_pt character varying(192) COLLATE pg_catalog."default",
    own_bus_seg_eaf_id numeric(18,0),
    CONSTRAINT pk_coverage PRIMARY KEY (coverage_id)
)

TABLESPACE pg_default;

ALTER TABLE public.ngha_cvg
    OWNER to postgres;